### ISSUE TITLE
verify_ssl issue

### ISSUE THREAD

**Issue by jamesthompson26-nhs** [NHSDigital/terraform-aws-mesh-client#93]
The verify_ssl option isn't able to properly validate the cert chain due to a (known) self-signed cert being present. Speaking with Matt this requires the mesh client library to be replaced with:

https://github.com/NHSDigital/mesh-client

**Comment by matt-mercer** [comment]
@jamesthompson26-nhs   believe closed by  https://github.com/NHSDigital/terraform-aws-mesh-client/pull/95  .. please let me know ..

**Comment by jamesthompson26-nhs** [comment]
Sorted 👍
